from __future__ import annotations

import json
import re
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from .artifacts import new_run_dir
from .candidate import CandidatePackage, package_skill_candidate
from .config import ManagerConfig
from .generator import GeneratedSkill, generate_skill_from_task
from .io import read_json, read_yaml, write_json
from .leaderboard import markdown_leaderboard, scan_episode_reports
from .llm_generator import generate_skill_from_task_llm
from .policy import PolicyResult, check_skill
from .publisher import PublishResult, publish_skill
from .reflection import build_feedback_prompt
from .registry import ToolRegistry, build_registry
from .runner import RunResult, run_published_skill
from .trace import pipeline_status_to_trace


_AUTH_FAILURE_RE = re.compile(
    r"(?<![A-Za-z0-9_.-])401(?![A-Za-z0-9_.-])|"
    r"(?<![A-Za-z0-9_])unauthorized(?![A-Za-z0-9_])",
    re.IGNORECASE,
)


def _has_auth_failure(text: str | None) -> bool:
    return bool(_AUTH_FAILURE_RE.search(text or ""))


@dataclass(frozen=True)
class AspireIterationResult:
    candidate_id: str
    task_path: str
    run_dir: str
    generated: dict[str, Any]
    package: dict[str, Any] | None
    policy: dict[str, Any]
    publish: dict[str, Any] | None
    episode_report: dict[str, Any]
    leaderboard: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def run_aspire_iteration(
    *,
    config: ManagerConfig,
    task_path: str | Path,
    candidate_id: str,
    generator_mode: str = "llm",
    llm_overrides: dict[str, Any] | None = None,
    llm_response_file: str | Path | None = None,
    llm_max_attempts: int = 2,
    execute: bool = False,
    publish: bool = True,
) -> AspireIterationResult:
    started_at = time.time()
    registry = build_registry(config)
    run_dir = new_run_dir(config.artifacts.runs_dir, candidate_id)
    if generator_mode == "template":
        generated = generate_skill_from_task(
            task_path=task_path,
            candidate_id=candidate_id,
            output_dir=run_dir / "generated",
            registry=registry,
        )
    elif generator_mode == "llm":
        generated = generate_skill_from_task_llm(
            task_path=task_path,
            candidate_id=candidate_id,
            output_dir=run_dir / "generated",
            registry=registry,
            llm_config=config.llm,
            llm_overrides=llm_overrides,
            response_file=llm_response_file,
            max_attempts=llm_max_attempts,
        )
    else:
        raise ValueError(f"unsupported generator mode: {generator_mode}")
    policy = check_skill(generated.local_path, registry)
    package: CandidatePackage | None = None
    publish_result: PublishResult | None = None
    run_result: RunResult | None = None
    run_error: str | None = None

    if policy.ok:
        package = package_skill_candidate(
            candidate_id=candidate_id,
            skill_yaml=generated.local_path,
            output_root=run_dir / "packages",
            registry=registry,
            hypothesis=_generated_metadata_str(generated, "hypothesis") or _task_hypothesis(task_path),
            change_summary=_generated_metadata_str(generated, "change_summary")
            or f"Generated by the first-stage ASPIRE-KW {generator_mode} loop.",
            expected_failure_modes=_generated_expected_failures(generated)
            or ["static policy violation", "KW pipeline failure", "vision service failure"],
            skill_args=_generated_skill_args(generated) or _task_args(task_path),
            overwrite=True,
        )
        if publish:
            publish_result = publish_skill(config=config, candidate_id=candidate_id, source_path=package.skill_path)
        if execute and publish_result is not None:
            try:
                run_result = run_published_skill(config=config, skill_path=publish_result.pipeline_skill_path, kwargs={})
            except Exception as exc:
                run_error = repr(exc)

    episode_report = build_episode_report(
        candidate_id=candidate_id,
        task_path=task_path,
        generated=generated,
        policy=policy,
        package=package,
        publish=publish_result,
        run_result=run_result,
        run_error=run_error,
        execute=execute,
        started_at=started_at,
    )
    write_json(run_dir / "episode_report.json", episode_report)
    if run_result is not None:
        write_json(run_dir / "aspire_trace.json", pipeline_status_to_trace(run_result.final_status))
    feedback_prompt = build_feedback_prompt(
        task=_task_payload(task_path),
        candidate_manifest=_load_manifest(package),
        episode_report=episode_report,
        registry_summary=registry.to_dict(),
    )
    (run_dir / "feedback_prompt.txt").write_text(feedback_prompt, encoding="utf-8")
    leaderboard = scan_episode_reports(config.artifacts.runs_dir)
    write_json(config.artifacts.runs_dir / "leaderboard.json", leaderboard)
    (config.artifacts.runs_dir / "leaderboard.md").write_text(markdown_leaderboard(leaderboard), encoding="utf-8")
    manifest = {
        "schema": "ksm.aspire_kw.evolution_manifest.v1",
        "run_dir": str(run_dir),
        "candidate_id": candidate_id,
        "execute": execute,
        "publish": publish,
        "generator_mode": generator_mode,
        "episode_report": episode_report,
        "leaderboard": leaderboard,
    }
    write_json(run_dir / "evolution_manifest.json", manifest)
    result = AspireIterationResult(
        candidate_id=candidate_id,
        task_path=str(Path(task_path).expanduser().resolve()),
        run_dir=str(run_dir),
        generated=generated.to_dict(),
        package=package.to_dict() if package else None,
        policy=policy.to_dict(),
        publish=publish_result.to_dict() if publish_result else None,
        episode_report=episode_report,
        leaderboard=leaderboard,
    )
    write_json(run_dir / "report.json", result.to_dict())
    return result


def build_episode_report(
    *,
    candidate_id: str,
    task_path: str | Path,
    generated: GeneratedSkill,
    policy: PolicyResult,
    package: CandidatePackage | None,
    publish: PublishResult | None,
    run_result: RunResult | None,
    run_error: str | None,
    execute: bool,
    started_at: float,
) -> dict[str, Any]:
    skill_success = _skill_success(run_result.final_status) if run_result else False
    success = bool(execute and skill_success and policy.ok and run_error is None)
    failure_signature = classify_failure(
        policy_ok=policy.ok,
        execute=execute,
        run_result=run_result,
        run_error=run_error,
    )
    return {
        "schema": "ksm.aspire_kw.episode_report.v1",
        "candidate_id": candidate_id,
        "task_id": generated.task_id,
        "task_path": str(Path(task_path).expanduser().resolve()),
        "success": success,
        "skill_success": skill_success,
        "policy_ok": policy.ok,
        "failure_signature": failure_signature,
        "duration_s": time.time() - started_at,
        "artifacts": {
            "generated_skill": generated.local_path,
            "candidate_package": package.package_dir if package else None,
            "published_skill": publish.published_path if publish else None,
        },
        "metadata": {
            "execute": execute,
            "generator": generated.metadata,
            "policy": policy.to_dict(),
            "publish": publish.to_dict() if publish else None,
            "run_result": run_result.to_dict() if run_result else None,
            "run_error": run_error,
        },
    }


def classify_failure(
    *,
    policy_ok: bool,
    execute: bool,
    run_result: RunResult | None,
    run_error: str | None,
) -> str:
    if not policy_ok:
        return "static_policy_violation"
    if not execute:
        return "dry_run"
    if run_error:
        lowered = run_error.lower()
        if _has_auth_failure(lowered):
            return "reasoning_unauthorized"
        return "execution_exception"
    if run_result is None:
        return "missing_run_result"
    status_text = json.dumps(run_result.final_status, ensure_ascii=False)
    lowered = status_text.lower()
    if _has_auth_failure(lowered):
        return "reasoning_unauthorized"
    if _skill_success(run_result.final_status):
        return "success"
    return "skill_execution_failed"


def _skill_success(status: dict[str, Any]) -> bool:
    response = status.get("response") if isinstance(status.get("response"), dict) else status
    success_items = response.get("success") if isinstance(response, dict) else None
    if isinstance(success_items, list) and success_items:
        latest = success_items[-1]
        return bool(isinstance(latest, dict) and latest.get("success"))
    return bool(response.get("success")) if isinstance(response, dict) else False


def _task_payload(path: str | Path) -> dict[str, Any]:
    data = read_yaml(path)
    return data if isinstance(data, dict) else {}


def _task_args(path: str | Path) -> dict[str, Any]:
    data = _task_payload(path)
    args = data.get("args")
    return dict(args) if isinstance(args, dict) else {}


def _task_hypothesis(path: str | Path) -> str:
    data = _task_payload(path)
    description = str(data.get("description") or data.get("task_id") or Path(path).stem)
    return f"KW YAML candidate can execute the requested continuous skill: {description}"


def _generated_metadata_str(generated: GeneratedSkill, key: str) -> str:
    value = generated.metadata.get(key)
    return str(value).strip() if value is not None else ""


def _generated_expected_failures(generated: GeneratedSkill) -> list[str]:
    value = generated.metadata.get("expected_failure_modes")
    if isinstance(value, list):
        return [str(item) for item in value]
    if isinstance(value, str) and value.strip():
        return [value.strip()]
    return []


def _generated_skill_args(generated: GeneratedSkill) -> dict[str, Any]:
    value = generated.metadata.get("skill_args")
    return dict(value) if isinstance(value, dict) else {}


def _load_manifest(package: CandidatePackage | None) -> dict[str, Any]:
    if package is None:
        return {}
    try:
        data = read_json(package.manifest_path)
    except Exception:
        return {}
    return data if isinstance(data, dict) else {}
